/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.henrique.view;

import br.com.henrique.control.TesteClienteControl;
import br.com.henrique.control.TestePanelControl;
import br.com.henrique.control.TesteServicoControl;
import br.com.henrique.uteis.ThereadRelogio;

/**
 *
 * @author ACER
 */
public class TESTE extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstacionamento
     */
    private TesteClienteControl clienteControl;
    private TesteServicoControl servicoControl;

    public TESTE() {
        initComponents();
        ThereadRelogio.start();
        clienteControl = new TesteClienteControl();
        servicoControl = new TesteServicoControl();
        TestePanelControl.carregarCarrosEstacionados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 530));

        tfMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 80, -1));

        tfNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, -1));

        tfModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 80, -1));

        cbTipo.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servidor", "Público" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, -1));

        try {
            tfPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("Cor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setText("Cadastrar Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("Marca");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jButton3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("Modelo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 10));

        labelCarros.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelCarros.setText("Cadastrar Carro");
        getContentPane().add(labelCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 0, 16)); // NOI18N
        jLabel3.setText("  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tfCor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, -1));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setText("Data");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        try {
            tfPlacaServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfPlacaServico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfPlacaServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 70, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setText("Placa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setText("Hora");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel10.setText("Entrada e Saída");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setText("Entrada");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 60, -1));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel12.setText("Valor");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        try {
            tfDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfDataSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 70, -1));

        try {
            tfDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfDataEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 70, -1));

        try {
            tfHoraSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfHoraSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHoraSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoraSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(tfHoraSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 40, -1));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setText("Placa");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jButton4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        tableCarrosEstacionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelEstacionados.setViewportView(tableCarrosEstacionados);

        panels.addTab("Carros Estacionados", panelEstacionados);

        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSalvar1.setText("Alterar");
        panelCliente.add(tbSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 80, 50));

        tbExcluir1.setText("Excluir");
        tbExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExcluir1ActionPerformed(evt);
            }
        });
        panelCliente.add(tbExcluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 80, 50));

        tableClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableClientes1);

        panelCliente.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        panelEditar.addTab("Cliente", panelCliente);

        panelCarro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSalvar2.setText("Alterar");
        panelCarro.add(tbSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 80, 50));

        tbExcluir2.setText("Excluir");
        tbExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExcluir2ActionPerformed(evt);
            }
        });
        panelCarro.add(tbExcluir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 80, 50));

        tableCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableCarros);

        panelCarro.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        panelEditar.addTab("Carro", panelCarro);

        panelServicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSalvar5.setText("Alterar");
        panelServicos.add(tbSalvar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 80, 50));

        tbExcluir5.setText("Excluir");
        tbExcluir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExcluir5ActionPerformed(evt);
            }
        });
        panelServicos.add(tbExcluir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 80, 50));

        tableServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableServicos);

        panelServicos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        panelEditar.addTab("Serviços", panelServicos);

        panels.addTab("Editar Arquivos", panelEditar);

        getContentPane().add(panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 740, 510));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setText("Saída");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        tfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        getContentPane().add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, -1));
        getContentPane().add(tfHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 40, -1));

        jMenu1.setText("Menu");

        jMenu4.setText("Adicionar");

        jMenuItem8.setText("Serviço");
        jMenu4.add(jMenuItem8);
        jMenuItem8.getAccessibleContext().setAccessibleDescription("");

        jMenuItem7.setText("Cliente");
        jMenu4.add(jMenuItem7);

        jMenuItem5.setText("Carro");
        jMenu4.add(jMenuItem5);

        jMenu1.add(jMenu4);

        jMenuItem11.setText("Home");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Arquivos");

        jMenuItem4.setText("Historico");
        jMenu2.add(jMenuItem4);

        jMenu3.setText("Editar");

        jMenuItem3.setText("Carros");
        jMenu3.add(jMenuItem3);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed
    /**
     * Salva carro e cliente
     *
     * @param evt
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clienteControl.salvarAction();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfHoraSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoraSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoraSaidaActionPerformed

    private void tbExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExcluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbExcluir1ActionPerformed

    private void tbExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExcluir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbExcluir2ActionPerformed

    private void tbExcluir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExcluir5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbExcluir5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        servicoControl.salvarServicoAction(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TESTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TESTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TESTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TESTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TESTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JComboBox<String> cbTipo = new javax.swing.JComboBox<>();
    public static final javax.swing.JButton jButton3 = new javax.swing.JButton();
    private javax.swing.JButton jButton4;
    public static final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static final javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
    private javax.swing.JToolBar jToolBar1;
    public static final javax.swing.JLabel labelCarros = new javax.swing.JLabel();
    public static final javax.swing.JPanel panelCarro = new javax.swing.JPanel();
    public static final javax.swing.JPanel panelCliente = new javax.swing.JPanel();
    public static final javax.swing.JTabbedPane panelEditar = new javax.swing.JTabbedPane();
    public static final javax.swing.JScrollPane panelEstacionados = new javax.swing.JScrollPane();
    private static final javax.swing.JPanel panelServicos = new javax.swing.JPanel();
    public static final javax.swing.JTabbedPane panels = new javax.swing.JTabbedPane();
    public static final javax.swing.JTable tableCarros = new javax.swing.JTable();
    public static final javax.swing.JTable tableCarrosEstacionados = new javax.swing.JTable();
    public static final javax.swing.JTable tableClientes1 = new javax.swing.JTable();
    public static final javax.swing.JTable tableServicos = new javax.swing.JTable();
    public static final javax.swing.JToggleButton tbExcluir1 = new javax.swing.JToggleButton();
    public static final javax.swing.JToggleButton tbExcluir2 = new javax.swing.JToggleButton();
    public static final javax.swing.JToggleButton tbExcluir5 = new javax.swing.JToggleButton();
    public static final javax.swing.JToggleButton tbSalvar1 = new javax.swing.JToggleButton();
    public static final javax.swing.JToggleButton tbSalvar2 = new javax.swing.JToggleButton();
    public static final javax.swing.JToggleButton tbSalvar5 = new javax.swing.JToggleButton();
    public static final javax.swing.JTextField tfCor = new javax.swing.JTextField();
    public static final javax.swing.JFormattedTextField tfDataEntrada = new javax.swing.JFormattedTextField();
    public static final javax.swing.JFormattedTextField tfDataSaida = new javax.swing.JFormattedTextField();
    public static final javax.swing.JTextField tfHoraEntrada = new javax.swing.JTextField();
    public static final javax.swing.JFormattedTextField tfHoraSaida = new javax.swing.JFormattedTextField();
    public static final javax.swing.JTextField tfMarca = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfModelo = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfNome = new javax.swing.JTextField();
    public static final javax.swing.JFormattedTextField tfPlaca = new javax.swing.JFormattedTextField();
    public static final javax.swing.JFormattedTextField tfPlacaServico = new javax.swing.JFormattedTextField();
    public static final javax.swing.JFormattedTextField tfValor = new javax.swing.JFormattedTextField();
    // End of variables declaration//GEN-END:variables
}
